export const LOAD_COFFEES_SUCCESS = 'LOAD_COFFEES_SUCCESS';
export const CREATE_COFFEE_SUCCESS = 'CREATE_COFFEE_SUCCESS';
export const UPDATE_COFFEE_SUCCESS = 'UPDATE_COFFEE_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const LOAD_ROAST_SUCCESS = 'LOAD_ROAST_SUCCESS';
export const CREATE_ROAST_SUCCESS = 'CREATE_ROAST_SUCCESS';
export const SET_COFFEEMIX_SUCCESS = 'SET_COFFEEMIX_SUCCESS';
export const SET_SELECTEDCOFFEE_SUCCESS = 'SET_SELECTEDCOFFEE_SUCCESS';

